workflows:
  android-app:
    name: Android ÇARX
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.wheel.carx"
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android app
        script: |
          cd $CM_BUILD_DIR
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
