name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          
      - name: Check directory
        run: |
          pwd
          ls -la
          
      - name: Make gradlew executable (if exists)
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x ./gradlew
          fi
          
      - name: Initialize Gradle (if needed)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle not found, initializing minimal project"
            mkdir -p app/src/main/java/com/wheel/carx
            mkdir -p app/src/main/res
            
            # Create basic Android project files
            echo 'plugins { id "com.android.application" }
            android {
              compileSdkVersion 31
              defaultConfig {
                applicationId "com.wheel.carx"
                minSdkVersion 21
                targetSdkVersion 31
                versionCode 1
                versionName "1.0"
              }
              buildTypes {
                release { minifyEnabled false }
              }
            }
            dependencies {
              implementation "androidx.appcompat:appcompat:1.4.1"
            }' > app/build.gradle
            
            echo 'buildscript {
              repositories { google(); mavenCentral() }
              dependencies {
                classpath "com.android.tools.build:gradle:7.0.4"
              }
            }
            allprojects {
              repositories { google(); mavenCentral() }
            }' > build.gradle
            
            echo 'include ":app"' > settings.gradle
            
            # Create Gradle wrapper
            gradle wrapper
          fi
          
      - name: Build APK
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug || true
          else
            echo "Gradle wrapper not found"
          fi
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/
